### ISSUE TITLE
Code Execution

### ISSUE THREAD

**Issue by robryanx** [Rockstar04/SublimeLinter-contrib-phpstan#5]
This plugin seems dangerous in that it is specifying the file being analysed as the autoload file as well. phpstan will execute the autoload file which isn't expected from a static analysis tool and could be very dangerous for scripts with side effects.

**Comment by Rockstar04** [comment]
PHPStan itself also executes code when doing its analysis. https://github.com/phpstan/phpstan/issues/67

Adding the ability to configure what file is set as the autoloader could be great for projects that are using composer or some other auto loading system, but for now loading the file itself allows most of the benefits of PHPStan in the widest range of projects.

**Comment by bustbr** [comment]
Using this plugin is **_seriously dangerous_** and not fixing this broken behavior is outright _negligent_.
People discover this plugin via Package Control, which seems like a somewhat trustworthy source, they don't expect accidental code execution.

Right now **every time the linter runs all the code in the file is executed**.
That's absolutely ridiculous!

The default behavior shouldn't be to set the file that's being analyzed as autoloader-file. This has nothing to do with the problem that PHPStan itself has a similarly horrible side-effect – which they're actively working on to get rid of, as far as I understand the issue you linked.

> loading the file itself allows most of the benefits of PHPStan in the widest range of projects.

That's not even true. The *only* projects that benefit from this hazardous behavior are those that `include` all dependencies manually in every file, and even then you're still **executing all the code on every run of the linter**.

I think it's fair to say most modern PHP projects are using composer anyway; even this project suggests using composer to install PHPStan itself.
A sensible default might therefore be to find the `vendor/autoload.php` file for the current project (e.g. by using Sublime's `$project_path` or maybe better yet by traversing the file system tree upwards, looking for a `composer.json` or `composer.lock` file), or just don't autoload anything by default and, like you said, make it configurable.

**Please fix this package or remove it from Package Control and add a fat warning to the README.**

This is also the reason for issue #1 by the way. Because PHP cannot run the file without errors PHPStan aborts. So setting the file-to-be-linted as autoload-file also breaks the linter when it would be needed most, i.e. when the code is broken.

**Comment by Rockstar04** [comment]
Thanks for the comment @bustbr, feel free to submit a pull request! You may also have not noticed that PHPStan itself also executes code when doing its analysis. https://github.com/phpstan/phpstan/issues/67

**Comment by Rockstar04** [comment]
Addressed in #6
